id: P003008
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 2021-12-17 10:34:01.718203
source_metadata:
  id: bdr:W29666
  title: རྟགས་འཇུག་དཀའ་གནད་གསལ་བའི་མེ་ལོང་གི་དྲི་ལན་དབྱངས་ཅན་དགྱེས་པའི་མཆོད་སྤྲིན།
  author: ''
  volumes:
    e6c2d3ab5cd84cfb9b2ee94e058593e0:
      image_group_id: I5553
      title: ''
      volume_number: 1
      total_pages: 43
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
