id: I370349F7
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T05:26:48+00:00'
last_modified: '2022-06-07T16:58:06.922594+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W29666
  title: རྟགས་འཇུག་དཀའ་གནད་གསལ་བའི་མེ་ལོང་གི་དྲི་ལན་དབྱངས་ཅན་དགྱེས་པའི་མཆོད་སྤྲིན།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    44F9:
      image_group_id: I5553
      title: ''
      total_pages: 43
      order: 1
      base_file: 44F9.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
